#
# Copyright (C) 2021 Acusp
#
# <https://github.com/acusp/OpenWrt-Actions>
#
# Thanks for: https://github.com/kenzok8
#

name: Update packages

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 */1 * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/acusp/OpenWrt-Packages.git

jobs:
  build:
    name: Update Packages
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        chmod +x pkg-list.sh
        git clone --depth 1 $REPO_URL packages
        cd packages
        rm -rf *
        $GITHUB_WORKSPACE/pkg-list.sh

    - name: Update packages
      working-directory: ./packages
      run: |
        msg=$(git diff --stat | tail -1)
        git add .
        if [ -z $msg ];then
          git commit -m "Sync: add new content"
        else
          git commit -m "Sync: $msg"
        fi
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/acusp/OpenWrt-Packages.git"
