#
# Copyright (C) 2021 Acusp
#
# <https://github.com/acusp/OpenWrt-Packages>
#
# Thanks for: https://github.com/kenzok8
#

name: Update packages

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 */1 * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Update & Build OpenWrt
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x customize.sh
        git clone https://github.com/acusp/OpenWrt-Packages.git
        cd OpenWrt-Packages
        $GITHUB_WORKSPACE/customize.sh

    - name: Update packages
      run: |
        cd $GITHUB_WORKSPACE/OpenWrt-Packages
        git add .
        git commit -m "Update: auto sync upstream$\n $(git diff --name-only HEAD~ HEAD) $(date +-%Y%m%d)"
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/acusp/OpenWrt-Packages.git"
